source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_pr60__itemize_enumerate_nested__input__itemize_enumerate_nested/src__.current__latex_docling_groundtruth__batch_pr60__itemize_enumerate_nested__input__itemize_enumerate_nested.tex"
sha256 = "19e61667dd4a128b3c37be5153f104ec0caf4b38b89cd8717fa137ee6d8c6b11"
bytes = 223
