source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_002__det_footnote__input__det_footnote/src__.current__latex_docling_groundtruth__batch_002__det_footnote__input__det_footnote.tex"
sha256 = "9254b89cdd2fc1ed112fe98fc08f8a78aa0cdd0b8347f3ecdf22fa2bf4fa60d5"
bytes = 175
