source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_002__det_figure_reference__input__det_figure_reference/src__.current__latex_docling_groundtruth__batch_002__det_figure_reference__input__det_figure_reference.tex"
sha256 = "7bb73aab2f1092c27c5aef0d9d2292aa1447719be4d700a27ad5780dd85096fa"
bytes = 254
