source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_pr60__multipage_all_features_references_footnotes__input__multipage_all_features_references_footnotes/src__.current__latex_docling_groundtruth__batch_pr60__multipage_all_features_references_footnotes__input__multipage_all_features_references_footnotes.tex"
sha256 = "6bb080152d912f0fdd34cf624253b1d46d9fe0e54ef431d3abb0e08315b43f54"
bytes = 8801
