"""Pydantic data contracts for the pdf2md pipeline.

Re-exports the IR, entity, prior, linked-structure, and export contracts
used across `connectors/`, `consensus/`, `calibration/`, `linking/`, and
`export/`. Importing names from `pdf2md.models` is preferred over
importing from the individual submodules.
"""

from .entities import (
    ENTITY_SCHEMA_VERSION,
    ConfidenceSource,
    EntityEvidence,
    EntityProposal,
    EntityProposalDocument,
    EntityType,
    EvidenceKind,
    RelationProposal,
    RelationType,
    entity_id,
    relation_id,
)
from .export import (
    EXPORT_SCHEMA_VERSION,
    ExportArtefact,
    ExportArtefactType,
    ExportManifestDocument,
    ExportStatus,
    RagChunk,
    RagChunkDocument,
    RagChunkType,
    rag_chunk_id,
)
from .ir import (
    SCHEMA_VERSION,
    BackendManifest,
    BlockKind,
    Conflict,
    ConflictKind,
    ConsensusBlock,
    ConsensusIR,
    ConsensusPage,
    CoordOrigin,
    ExtractionBlock,
    PageExtractionIR,
    PageSize,
    SelectionMode,
    Span,
    conflict_id,
    consensus_id,
    extraction_id,
)
from .ir import BBox as IRBBox
from .linked import (
    LINKED_SCHEMA_VERSION,
    LinkedConflict,
    LinkedNode,
    LinkedNodeType,
    LinkedRelation,
    LinkedRelationType,
    LinkedStructure,
    LinkEvidence,
    LinkEvidenceKind,
    LinkStatus,
    linked_conflict_id,
    linked_node_id,
    linked_relation_id,
)
from .priors import (
    PRIOR_SCHEMA_VERSION,
    CalibrationCounts,
    CalibrationMetric,
    CalibrationPriorDocument,
    CalibrationStatus,
    CalibrationTarget,
    CalibrationTruthDocument,
    MatchOutcome,
    TruthBlock,
    TruthEntity,
    TruthRelation,
    lookup_confidence,
    lookup_prior,
    prior_key,
)

__all__ = [
    "ENTITY_SCHEMA_VERSION",
    "EXPORT_SCHEMA_VERSION",
    "LINKED_SCHEMA_VERSION",
    "PRIOR_SCHEMA_VERSION",
    "SCHEMA_VERSION",
    "BackendManifest",
    "BlockKind",
    "CalibrationCounts",
    "CalibrationMetric",
    "CalibrationPriorDocument",
    "CalibrationStatus",
    "CalibrationTarget",
    "CalibrationTruthDocument",
    "ConfidenceSource",
    "Conflict",
    "ConflictKind",
    "ConsensusBlock",
    "ConsensusIR",
    "ConsensusPage",
    "CoordOrigin",
    "EntityEvidence",
    "EntityProposal",
    "EntityProposalDocument",
    "EntityType",
    "EvidenceKind",
    "ExportArtefact",
    "ExportArtefactType",
    "ExportManifestDocument",
    "ExportStatus",
    "ExtractionBlock",
    "IRBBox",
    "LinkEvidence",
    "LinkEvidenceKind",
    "LinkStatus",
    "LinkedConflict",
    "LinkedNode",
    "LinkedNodeType",
    "LinkedRelation",
    "LinkedRelationType",
    "LinkedStructure",
    "MatchOutcome",
    "PageExtractionIR",
    "PageSize",
    "RagChunk",
    "RagChunkDocument",
    "RagChunkType",
    "RelationProposal",
    "RelationType",
    "SelectionMode",
    "Span",
    "TruthBlock",
    "TruthEntity",
    "TruthRelation",
    "conflict_id",
    "consensus_id",
    "entity_id",
    "extraction_id",
    "linked_conflict_id",
    "linked_node_id",
    "linked_relation_id",
    "lookup_confidence",
    "lookup_prior",
    "prior_key",
    "rag_chunk_id",
    "relation_id",
]
