from .document import BBox, Block, Document, Flag, Page, SourceRef
from .ir import (
    BackendManifest,
    BlockKind,
    Conflict,
    ConflictKind,
    ConsensusBlock,
    ConsensusIR,
    ConsensusPage,
    CoordOrigin,
    ExtractionBlock,
    PageExtractionIR,
    PageSize,
    SCHEMA_VERSION,
    SelectionMode,
    Span,
    conflict_id,
    consensus_id,
    extraction_id,
)
from .ir import BBox as IRBBox

from .entities import (
    ENTITY_SCHEMA_VERSION,
    ConfidenceSource,
    EntityEvidence,
    EntityProposal,
    EntityProposalDocument,
    EntityType,
    EvidenceKind,
    RelationProposal,
    RelationType,
    entity_id,
    relation_id,
)

__all__ = [
    "BBox",
    "Block",
    "Document",
    "Flag",
    "Page",
    "SourceRef",
    "SCHEMA_VERSION",
    "CoordOrigin",
    "BlockKind",
    "SelectionMode",
    "ConflictKind",
    "IRBBox",
    "Span",
    "PageSize",
    "ExtractionBlock",
    "PageExtractionIR",
    "Conflict",
    "ConsensusBlock",
    "ConsensusPage",
    "BackendManifest",
    "ConsensusIR",
    "extraction_id",
    "consensus_id",
    "conflict_id",
    "ENTITY_SCHEMA_VERSION",
    "ConfidenceSource",
    "EntityEvidence",
    "EntityProposal",
    "EntityProposalDocument",
    "EntityType",
    "EvidenceKind",
    "RelationProposal",
    "RelationType",
    "entity_id",
    "relation_id",
]
