source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_pr60__multiple_equations_references__input__multiple_equations_references/src__.current__latex_docling_groundtruth__batch_pr60__multiple_equations_references__input__multiple_equations_references.tex"
sha256 = "f8512af0f557a9da4455831b1c1395702cc61b6ca77bce90a6216317e2e0edfd"
bytes = 269
