source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_001__unnumbered_sections__input__unnumbered_sections/src__.current__latex_docling_groundtruth__batch_001__unnumbered_sections__input__unnumbered_sections.tex"
sha256 = "ae43578223068af85e64b38e4d89b69efc2b1e9c88e0e074551a7a35a308136f"
bytes = 223
