source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_pr60__footnote_inside_list__input__footnote_inside_list/src__.current__latex_docling_groundtruth__batch_pr60__footnote_inside_list__input__footnote_inside_list.tex"
sha256 = "c43dd45cc794c81c36ae3d2a0aed4c2bde8fd95876c2b08b320b82a3a2223f37"
bytes = 189
