source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_002__det_all_features__input__det_all_features/src__.current__latex_docling_groundtruth__batch_002__det_all_features__input__det_all_features.tex"
sha256 = "4956ffda286ac660737775bab1a94b8fc35869fc383ee2e0b4d141fb35ab02a9"
bytes = 548
