source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_pr60__simple_title_paragraph__input__simple_title_paragraph/src__.current__latex_docling_groundtruth__batch_pr60__simple_title_paragraph__input__simple_title_paragraph.tex"
sha256 = "4e726ea0df1eab6e098eba4b5220a8d126c8161003c295767ab049f3dd867b72"
bytes = 178
