source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_001__complex_multi_reference_network__input__complex_multi_reference_network/src__.current__latex_docling_groundtruth__batch_001__complex_multi_reference_network__input__complex_multi_reference_network.tex"
sha256 = "719a9938b447f5493c1dc0e9c624890b79c249551f6cd4500f02add3dadda576"
bytes = 534
