source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_002__det_bibliography__input__det_bibliography/src__.current__latex_docling_groundtruth__batch_002__det_bibliography__input__det_bibliography.tex"
sha256 = "8f673b77c24206ab8955319f9b71622c0fe9e5668606d05fae082adfa61dd7fd"
bytes = 159
