source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_001__table_caption_reference__input__table_caption_reference/src__.current__latex_docling_groundtruth__batch_001__table_caption_reference__input__table_caption_reference.tex"
sha256 = "3daf6329e94686cfb2ad7a0fbcbdb46e094f97ab901cc15d6e6ef4c2a887fad5"
bytes = 276
