source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_001__all_features_small__input__all_features_small/src__.current__latex_docling_groundtruth__batch_001__all_features_small__input__all_features_small.tex"
sha256 = "f7a26b6b3a03e75d5814d9ad55402cd473f5d15db964dcd81e551ebb00f13ea8"
bytes = 639
