source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_001__footnotes_basic__input__footnotes_basic/src__.current__latex_docling_groundtruth__batch_001__footnotes_basic__input__footnotes_basic.tex"
sha256 = "0ec44db333f753b7f82fffdc5634404ff533942e8911896635e4a139aab05d17"
bytes = 195
