source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_pr60__two_figures_cross_references__input__two_figures_cross_references/src__.current__latex_docling_groundtruth__batch_pr60__two_figures_cross_references__input__two_figures_cross_references.tex"
sha256 = "78a8f9c3c84dec4c0699897cb5e99968ef7e4cca9f9f72d9b6aa742b11d2c157"
bytes = 332
