source_path = "groundtruth/corpus/latex/src__.current__docling_groundtruth__batch_001__linked_sections_figures__input__linked_sections_figures/src__.current__docling_groundtruth__batch_001__linked_sections_figures__input__linked_sections_figures.tex"
sha256 = "6c34844acc3d3fc93fea607b270c3d3fafe50faee879371e6d8ded63715a596e"
bytes = 830
