source_path = "groundtruth/corpus/latex/src__.current__docling_groundtruth__batch_001__lists_footnotes_tables__input__lists_footnotes_tables/src__.current__docling_groundtruth__batch_001__lists_footnotes_tables__input__lists_footnotes_tables.tex"
sha256 = "03ed89cbe411cdc1acf89ac06387095a00fb0387a54eccee3aae9da07e8586ea"
bytes = 1244
