source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_002__det_title_paragraph__input__det_title_paragraph/src__.current__latex_docling_groundtruth__batch_002__det_title_paragraph__input__det_title_paragraph.tex"
sha256 = "0a91931cdd1417ed7999c73a6f820b8171207c518687040a3978761d582165a4"
bytes = 165
