source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_pr60__bibliography_like_references__input__bibliography_like_references/src__.current__latex_docling_groundtruth__batch_pr60__bibliography_like_references__input__bibliography_like_references.tex"
sha256 = "40d5ffeea9107b795448569a5d814094b11a649f666e7d5850e0d24a9bc26888"
bytes = 211
