
# Detectable All Features


## 1 All


FIG


Figure 1: Boxed figure


Table 1: Sample table


A B


1 2


 \[ E=mc^{2} \quad (1) \] 


See Figure 1, Table 1, Eq. (1), and Section 1. \( ^{1} \)  As shown in [1].