source_path = "groundtruth/corpus/latex/src__.current__latex_docling_groundtruth__batch_002__det_equation_reference__input__det_equation_reference/src__.current__latex_docling_groundtruth__batch_002__det_equation_reference__input__det_equation_reference.tex"
sha256 = "96c8955367c1a5a1591cefc1c0214799c410d49372d505e332d9255ddfda513a"
bytes = 223
